-- 0009_phase6_content_infra.sql
--
-- Phase 6 — Content infrastructure: Cloudflare Stream signed playback,
-- R2 storage for certificates / generic uploads, Cloudflare Images,
-- MailChannels transactional email log.
--
-- All tables are additive. The existing modules.video_uid column already
-- holds the Stream UID — we add `lesson_uploads` to track upload lifecycle
-- (direct creator URLs, processing → ready transitions via webhook).
--
-- Apply with:
--   wrangler d1 execute tokenomic-db --file=./migrations/0009_phase6_content_infra.sql --remote

-- Stream upload lifecycle. One row per direct-creator-URL request. The
-- module / course is linked when the educator picks a lesson; the row
-- transitions to ready=1 when the Stream webhook fires for that uid.
CREATE TABLE IF NOT EXISTS lesson_uploads (
  id              INTEGER PRIMARY KEY AUTOINCREMENT,
  stream_uid      TEXT NOT NULL UNIQUE,
  course_id       INTEGER,
  module_id       INTEGER,
  owner_wallet    TEXT NOT NULL,
  state           TEXT NOT NULL DEFAULT 'pending',  -- pending | uploaded | ready | error
  duration_sec    INTEGER,
  size_bytes      INTEGER,
  meta            TEXT,                              -- JSON
  created_at      TEXT NOT NULL DEFAULT (datetime('now')),
  updated_at      TEXT NOT NULL DEFAULT (datetime('now'))
);
CREATE INDEX IF NOT EXISTS idx_lesson_uploads_owner ON lesson_uploads(owner_wallet);
CREATE INDEX IF NOT EXISTS idx_lesson_uploads_module ON lesson_uploads(module_id);

-- Generic R2 object registry. Used for avatars, course PDFs, certificate
-- PDFs and any other binary the worker stores. The bucket binding is
-- `R2_BUCKET`; signed GETs are minted by the worker.
CREATE TABLE IF NOT EXISTS r2_objects (
  id            INTEGER PRIMARY KEY AUTOINCREMENT,
  r2_key        TEXT NOT NULL UNIQUE,
  owner_wallet  TEXT,
  kind          TEXT NOT NULL,                       -- avatar | certificate | course-asset | misc
  content_type  TEXT,
  size_bytes    INTEGER,
  sha256        TEXT,
  visibility    TEXT NOT NULL DEFAULT 'private',     -- public | private
  meta          TEXT,                                -- JSON
  created_at    TEXT NOT NULL DEFAULT (datetime('now'))
);
CREATE INDEX IF NOT EXISTS idx_r2_owner ON r2_objects(owner_wallet);
CREATE INDEX IF NOT EXISTS idx_r2_kind  ON r2_objects(kind);

-- Cloudflare Images registry. CF Images returns an `id` we use to build
-- delivery URLs (https://imagedelivery.net/<account-hash>/<id>/<variant>).
CREATE TABLE IF NOT EXISTS cf_images (
  id             INTEGER PRIMARY KEY AUTOINCREMENT,
  cf_image_id    TEXT NOT NULL UNIQUE,
  owner_wallet   TEXT,
  kind           TEXT NOT NULL,                      -- thumbnail | article-cover | avatar | misc
  variants       TEXT,                                -- JSON array of variant URLs
  meta           TEXT,                                -- JSON
  created_at     TEXT NOT NULL DEFAULT (datetime('now'))
);
CREATE INDEX IF NOT EXISTS idx_cf_images_owner ON cf_images(owner_wallet);

-- Transactional email send log. Mirrors the invite log pattern from
-- referrals.js but tracks all generic sends (enrollment confirmation,
-- certificate issued, course published notification, etc).
CREATE TABLE IF NOT EXISTS email_log (
  id             INTEGER PRIMARY KEY AUTOINCREMENT,
  recipient      TEXT NOT NULL,
  template       TEXT NOT NULL,
  subject        TEXT,
  status         TEXT NOT NULL DEFAULT 'queued',    -- queued | sent | failed
  error          TEXT,
  message_id     TEXT,
  meta           TEXT,                               -- JSON
  created_at     TEXT NOT NULL DEFAULT (datetime('now')),
  sent_at        TEXT
);
CREATE INDEX IF NOT EXISTS idx_email_log_recipient ON email_log(recipient);
CREATE INDEX IF NOT EXISTS idx_email_log_template  ON email_log(template, created_at);

-- Issued certificates. One row per (course, student) PDF generated by the
-- educator's "Issue" action. The on-chain mint hash (TokenomicCertificate
-- ERC-1155) is recorded when available so the learner can prove ownership.
CREATE TABLE IF NOT EXISTS certificates_issued (
  id              INTEGER PRIMARY KEY AUTOINCREMENT,
  course_id       INTEGER NOT NULL,
  student_wallet  TEXT NOT NULL,
  educator_wallet TEXT NOT NULL,
  enrollment_id   INTEGER,
  pdf_r2_key      TEXT,
  pdf_sha256      TEXT,
  on_chain_tx     TEXT,
  email           TEXT,
  email_status    TEXT,                              -- sent | failed | skipped
  issued_at       TEXT NOT NULL DEFAULT (datetime('now')),
  UNIQUE(course_id, student_wallet)
);
CREATE INDEX IF NOT EXISTS idx_cert_student ON certificates_issued(student_wallet);
CREATE INDEX IF NOT EXISTS idx_cert_course  ON certificates_issued(course_id);
